version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - mlopez-grupopv
  labels:
  - dependencies
  - ruby
