version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
      timezone: "America/Chihuahua"
    open-pull-requests-limit: 10
    reviewers: ["mlopez-grupopv"]
    labels:
      - dependencies
      - ruby
