PRODUCT/1: ["product-2", "product-2", "product-3", "product-4", "product-5", "product-6"]
PRODUCT/2: ["product-1", "product-3", "product-4", "product-5"]
PRODUCT/4: ["product-1", "product-2", "product-3", "product-4", "product-5"]
PRODUCT/5: ["product-1", "product-2", "product-3", "product-4", "product-5"]
