version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "daily"
    default_reviewers: ["mlopez-grupopv"]
    default_labels:
      - dependencies
      - ruby
